Nama              : (input("Nama                : "))
NIM               : (input("NIM                 : "))
KelasParalel      : (input("Kelas Paralel       : "))
TempatTanggalLahir: (input("Tempat Tanggal Lahir: "))
Alamat            : (input("Alamat              : "))
Hobby             : (input("Hobby               : "))
NoHP              : (input("No HP               : "))
